
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5, 4, N'Виктория', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (16, 4, N'Западная Австралия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (23, 4, N'Кинсленд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (35, 4, N'Новый Южный Уэльс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (51, 4, N'Северная Территория', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (54, 4, N'Тасмания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (58, 4, N'Территория Федеральной столицы', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (60, 4, N'Южная Австралия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (64, 63, N'Вена', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (66, 63, N'Верхняя Австрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (70, 63, N'Зальцбург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (72, 63, N'Каринтия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (75, 63, N'Нижняя Австрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (77, 63, N'Штирия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (82, 81, N'Азербайджан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (164, 81, N'Нагорный Карабах', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (167, 81, N'Нахичеванская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (174, 173, N'Anguilla', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (178, 177, N'Буэнос-Айрес', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (194, 177, N'Жужуй', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (196, 177, N'Катамарка', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (198, 177, N'Кордоба', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (204, 177, N'Корриентес', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (207, 177, N'Ла-Пампа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (210, 177, N'Ла-Риоха', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (212, 177, N'Мендоса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (215, 177, N'Мисьонес', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (217, 177, N'Неукен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (219, 177, N'Сальта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (221, 177, N'Сан-Луис', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (223, 177, N'Сан-Хуан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (225, 177, N'Санта-Крус', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (227, 177, N'Санта-Фе', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (230, 177, N'Сантьяго-дель-Эстеро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (232, 177, N'Тукуман', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (234, 177, N'Формоса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (236, 177, N'Чако', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (239, 177, N'Чубут', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (241, 177, N'Энтре-Риос', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (246, 245, N'Ереванская область', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (249, 248, N'Брестская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (272, 248, N'Витебская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (304, 248, N'Гомельская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (330, 248, N'Гродненская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (349, 248, N'Минская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (377, 248, N'Могилевская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (402, 401, N'Belize', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (405, 404, N'Антверпен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (408, 404, N'Брюссель', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (410, 404, N'Восточная Фландрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (413, 404, N'Западная Фландрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (417, 404, N'Лимбург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (419, 404, N'Льеж', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (422, 404, N'Эно', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (426, 425, N'Hamilton', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (429, 428, N'Бургас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (431, 428, N'Варна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (433, 428, N'Великотырново', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (436, 428, N'Видин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (438, 428, N'Габрово', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (440, 428, N'Пазарджик', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (442, 428, N'Перник', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (444, 428, N'Плевен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (446, 428, N'Пловдив', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (449, 428, N'Русе', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (451, 428, N'Силистра', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (453, 428, N'Сливен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (455, 428, N'София град', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (457, 428, N'Стара Загора', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (460, 428, N'Хасково', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (463, 428, N'Шумен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (465, 428, N'Ямбол', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (468, 467, N'Акри', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (470, 467, N'Алагоас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (473, 467, N'Амазонас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (475, 467, N'Амапа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (477, 467, N'Баия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (490, 467, N'Гояс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (493, 467, N'Мараньян', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (497, 467, N'Мату-Гросу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (499, 467, N'Мату-Гросу-ду-Сул', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (503, 467, N'Минас-Жерайс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (521, 467, N'Пара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (524, 467, N'Параиба', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (527, 467, N'Парана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (533, 467, N'Пернамбуку', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (539, 467, N'Пиауи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (542, 467, N'Рио-де-Жанейро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (550, 467, N'Риу-Гранди-ду-Норти', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (554, 467, N'Риу-Гранди-ду-Сул', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (568, 467, N'Рондония', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (570, 467, N'Сан-Паулу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (595, 467, N'Санта-Катарина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (603, 467, N'Сеара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (609, 467, N'Сержипи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (611, 467, N'Федеральный округ', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (613, 467, N'Эспириту-Санту', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (617, 616, N'Англия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (881, 616, N'Северная Ирландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (889, 616, N'Уэльс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (899, 616, N'Шотландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (925, 924, N'Jasz-Nagykun-Szolnok', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (928, 924, N'Баранья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (930, 924, N'Бач-Кишкун', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (934, 924, N'Бекеш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (936, 924, N'Боршод-Абауй-Земплен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (939, 924, N'Будапешт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (941, 924, N'Ваш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (943, 924, N'Веспрем', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (945, 924, N'Дьёр-Шопрон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (947, 924, N'Зала', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (950, 924, N'Комаром', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (952, 924, N'Ноград', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (954, 924, N'Пешт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (956, 924, N'Сабольч-Сатмар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (958, 924, N'Фейер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (961, 924, N'Хайду-Бихар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (964, 924, N'Хевеш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (967, 924, N'Чонград', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (972, 971, N'Dong Bang Song Cuu Long', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (975, 971, N'Dong Bang Song Hong', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (979, 971, N'Dong Nam', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (982, 971, N'Duyen Hai Mien Trung', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (987, 971, N'Khu Bon', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (990, 971, N'Mien Nui Va Trung', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (992, 971, N'Thai Nguyen', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (995, 994, N'Artibonite', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (997, 994, N'GrandAnse', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (999, 994, N'Nord-Ouest', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1001, 994, N'Ouest', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1003, 994, N'Sud', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1005, 994, N'Sud-Est', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1008, 1007, N'Grande-Terre', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1010, 1007, N'Бас-Тер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1013, 1012, N'Berlin', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1015, 1012, N'Brandenburg', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1020, 1012, N'Mecklenburg-Vorpommern', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1028, 1012, N'Sachsen', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1043, 1012, N'Sachsen-Anhalt', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1053, 1012, N'Thuringen', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1064, 1012, N'Бавария', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1083, 1012, N'Баден-Вюртемберг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1103, 1012, N'Бремен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1106, 1012, N'Гамбург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1108, 1012, N'Гессен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1120, 1012, N'Нижняя Саксония', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1137, 1012, N'Рейнланд-Пфальц', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1149, 1012, N'Саарская область', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1152, 1012, N'Северный Рейн-Вестфалия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1201, 1012, N'Шлезвиг-Гольштейн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1207, 1206, N'Гелдерланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1213, 1206, N'Гронинген', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1215, 1206, N'Дренте', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1217, 1206, N'Лимбург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1222, 1206, N'Оверэйсел', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1227, 1206, N'Северная Голландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1235, 1206, N'Северный Брабант', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1240, 1206, N'Утрехт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1244, 1206, N'Фрисландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1246, 1206, N'Южная Голландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1259, 1258, N'Ahaia', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1261, 1258, N'Attiki', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1264, 1258, N'Drama', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1266, 1258, N'Evros', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1268, 1258, N'Hania', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1270, 1258, N'Ioannina', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1272, 1258, N'Iraklion', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1274, 1258, N'Kavala', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1276, 1258, N'Magnisia', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1278, 1258, N'Thessaloniki', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1281, 1280, N'Абхазия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1292, 1280, N'Аджария', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1296, 1280, N'Грузия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1363, 1280, N'Южная Осетия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1367, 1366, N'Baйле', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1369, 1366, N'Ceверная Ютландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1371, 1366, N'Opxyс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1374, 1366, N'Pocкилле', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1376, 1366, N'Pибе', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1378, 1366, N'Фюн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1381, 1380, N'Аль-Кахира', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1383, 1380, N'Асуан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1385, 1380, N'Асьют', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1387, 1380, N'Бени-Суэйф', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1389, 1380, N'Гарбия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1391, 1380, N'Думьят', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1394, 1393, N'Хадаром', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1403, 1393, N'Хамеркац', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1416, 1393, N'Хацафон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1429, 1393, N'Хефа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1440, 1393, N'Тель-Авив', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1449, 1393, N'Иерусалим', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1452, 1451, N'Bangla', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1468, 1451, N'Chhattisgarh', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1473, 1451, N'Karnataka', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1488, 1451, N'Uttaranchal', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1491, 1451, N'Андхра-Прадеш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1509, 1451, N'Ассам', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1512, 1451, N'Бихар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1521, 1451, N'Гуджарат', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1539, 1451, N'Джамму и Кашмир', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1545, 1451, N'Керала', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1548, 1451, N'Мадхья-Прадеш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1561, 1451, N'Манипур', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1563, 1451, N'Махараштра', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1586, 1451, N'Мегхалая', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1588, 1451, N'Орисса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1591, 1451, N'Пенджаб', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1596, 1451, N'Пондишери', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1598, 1451, N'Раджастхан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1612, 1451, N'Тамилнад', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1629, 1451, N'Трипура', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1631, 1451, N'Уттар-Прадеш', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1656, 1451, N'Харьяна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1661, 1451, N'Чандигарх', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1664, 1663, N'Azarbayjan-e Khavari', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1667, 1663, N'Esfahan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1669, 1663, N'Hamadan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1671, 1663, N'Kordestan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1673, 1663, N'Markazi', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1675, 1663, N'Sistan-e Baluches', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1677, 1663, N'Yazd', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1679, 1663, N'Керман', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1681, 1663, N'Керманшахан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1683, 1663, N'Мазендеран', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1686, 1663, N'Тегеран', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1688, 1663, N'Фарс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1691, 1663, N'Хорасан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1693, 1663, N'Хузистан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1697, 1696, N'Cork', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1699, 1696, N'Dublin', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1702, 1696, N'Limerick', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1704, 1696, N'Waterford', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1708, 1707, N'Cantabria', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1710, 1707, N'Ceuta', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1712, 1707, N'Granada', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1714, 1707, N'La Rioja', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1716, 1707, N'Salamanca', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1718, 1707, N'Алава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1720, 1707, N'Аликанте', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1724, 1707, N'Альбасете', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1726, 1707, N'Альмерия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1728, 1707, N'Астурия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1731, 1707, N'Барселона', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1738, 1707, N'Бискайя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1740, 1707, N'Бургос', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1742, 1707, N'Валенсия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1744, 1707, N'Валья­долид', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1746, 1707, N'Кадис', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1749, 1707, N'Касерес', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1753, 1707, N'Кордова', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1755, 1707, N'Лас-Пальмас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1757, 1707, N'Леон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1759, 1707, N'Лерида', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1761, 1707, N'Луго', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1763, 1707, N'Мадрид', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1765, 1707, N'Малага', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1767, 1707, N'Мурсия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1769, 1707, N'Острова Балеарские', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1771, 1707, N'Паленсия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1774, 1707, N'Самора', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1776, 1707, N'Санта-Крус-де-Тенерифе', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1778, 1707, N'Сарагоса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1780, 1707, N'Севилья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1782, 1707, N'Сьюдад-Реаль', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1784, 1707, N'Хаэн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1787, 1786, N'Абруцци', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1789, 1786, N'Апулия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1802, 1786, N'Венеция', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1806, 1786, N'Калабрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1810, 1786, N'Кампания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1819, 1786, N'Лацио', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1821, 1786, N'Лигурия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1826, 1786, N'Ломбардия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1838, 1786, N'Марке', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1841, 1786, N'О. Сардиния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1844, 1786, N'О. Сицилия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1858, 1786, N'Пьемонт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1864, 1786, N'Тоскана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1876, 1786, N'Трентино-Альто-Адидже', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1879, 1786, N'Умбрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1882, 1786, N'Фриули-Венеция-Джулия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1885, 1786, N'Эмилия-Романья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1895, 1894, N'Актюбинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1911, 1894, N'Алма-Атинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1924, 1894, N'Восточно-Казахстанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1942, 1894, N'Гурьевская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1954, 1894, N'Джамбулская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1974, 1894, N'Джезказганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1994, 1894, N'Карагандинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2010, 1894, N'Кзыл-Ординская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2021, 1894, N'Кокчетавская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2040, 1894, N'Кустанайская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2055, 1894, N'Мангышлакская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2061, 1894, N'Павлодарская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2074, 1894, N'Северо-Казахстанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2084, 1894, N'Семипалатинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2105, 1894, N'Талды-Курганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2120, 1894, N'Тургайская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2128, 1894, N'Целиноградская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2146, 1894, N'Чимкентская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2164, 2163, N'Littoral', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2166, 2163, N'Sudouest', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2168, 2163, N'Северная', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2170, 2163, N'Центральная', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2173, 2172, N'Альберта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2181, 2172, N'Британская Колумбия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2201, 2172, N'Квебек', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2229, 2172, N'Манитоба', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2232, 2172, N'Новая Шотландия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2235, 2172, N'Нью-Брунсвик', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2239, 2172, N'Ньюфаундленд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2242, 2172, N'Онтарио', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2291, 2172, N'Принц Эдуард', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2293, 2172, N'Саскачеван', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2298, 2297, N'Government controlled area', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2300, 2297, N'Turkish controlled area', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2304, 2303, N'Иссык-Кульская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2316, 2303, N'Кыргызстан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2327, 2303, N'Нарынская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2340, 2303, N'Ошская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2365, 2303, N'Таласская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2375, 2374, N'Xinjiang', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2379, 2374, N'Внутренняя Монголия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2382, 2374, N'Ганьсу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2386, 2374, N'Гуанси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2388, 2374, N'Ляонин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2393, 2374, N'Сычуань', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2396, 2374, N'Фуцзянь', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2398, 2374, N'Хубэй', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2401, 2374, N'Хунань', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2404, 2374, N'Хэбэй', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2406, 2374, N'Хэйлунцзян', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2408, 2374, N'Хэнань', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2411, 2374, N'Цзилинь', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2414, 2374, N'Цзянси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2416, 2374, N'Цзянсу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2419, 2374, N'Чжэцзян', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2424, 2374, N'Шанхай', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2426, 2374, N'Шаньдун', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2428, 2374, N'Шаньси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2431, 2430, N'Alajuela', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2433, 2430, N'Guanacaste', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2435, 2430, N'Heredia', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2437, 2430, N'Limon', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2439, 2430, N'Puntarenas', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2441, 2430, N'San Jose', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2444, 2443, N'al-Jahra', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2446, 2443, N'al-Kuwayt', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2449, 2448, N'Латвия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2510, 2509, N'Tarabulus', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2512, 2509, N'Бенгази', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2515, 2514, N'Литва', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2615, 2614, N'Люксембург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2618, 2617, N'Агуаскальентес', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2620, 2617, N'Веракрус', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2639, 2617, N'Герреро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2646, 2617, N'Гуанахуато', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2656, 2617, N'Дуранго', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2661, 2617, N'Идальго', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2666, 2617, N'Кампече', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2668, 2617, N'Керетаро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2670, 2617, N'Керетаро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2672, 2617, N'Коауила', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2679, 2617, N'Колима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2683, 2617, N'Мехико', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2690, 2617, N'Мичоакан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2700, 2617, N'Морелос', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2704, 2617, N'Наярит', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2709, 2617, N'Нижняя Калифорния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2713, 2617, N'Нуэво-Леон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2717, 2617, N'Оахака', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2725, 2617, N'Пуэбла', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2730, 2617, N'Сакатекас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2735, 2617, N'Сан-Луис-Потоси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2741, 2617, N'Синалоа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2746, 2617, N'Сонора', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2755, 2617, N'Табаско', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2759, 2617, N'Тамаулипас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2766, 2617, N'Федеральный округ', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2768, 2617, N'Халиско', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2778, 2617, N'Чиуауа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2780, 2617, N'Чьяпас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2786, 2617, N'Юкатан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2789, 2788, N'Молдова', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2834, 2833, N'Монако', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2838, 2837, N'Auckland', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2841, 2837, N'Bay of Plenty', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2844, 2837, N'Canterbury', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2847, 2837, N'Gisborne', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2849, 2837, N'Hawkes Bay', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2852, 2837, N'Manawatu-Wanganui', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2855, 2837, N'Marlborough', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2857, 2837, N'Nelson', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2859, 2837, N'Northland', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2861, 2837, N'Otago', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2863, 2837, N'Southland', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2866, 2837, N'Taranaki', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2869, 2837, N'Tasman', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2871, 2837, N'Waikato', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2874, 2837, N'Wellington', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2878, 2837, N'West Coast', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2881, 2880, N'Бускеруд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2883, 2880, N'Вестагдер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2885, 2880, N'Нурлан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2887, 2880, N'Осло', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2889, 2880, N'Ругаланн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2891, 2880, N'Сёр-Трённелаг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2893, 2880, N'Телемарк', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2895, 2880, N'Хуралан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2898, 2897, N'Dolnoslaskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2919, 2897, N'Kujawsko-Pomorskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2929, 2897, N'Lubuskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2937, 2897, N'Malopolskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2958, 2897, N'Mazowieckie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2983, 2897, N'Podkarpackie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2994, 2897, N'Podlaskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3003, 2897, N'Pomorskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3018, 2897, N'Slaskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3049, 2897, N'Swietokrzyskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3056, 2897, N'Warminsko-Mazurskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3068, 2897, N'Wielkopolskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3090, 2897, N'Zachodnio-Pomorskie', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3101, 2897, N'Лодзинское', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3118, 2897, N'Люблинское', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3133, 2897, N'Опольское', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3142, 3141, N'Centro', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3144, 3141, N'O-ва Мадейра', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3146, 3141, N'Лисабон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3150, 3141, N'Орта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3157, 3156, N'Saint-Denis', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3160, 3159, N'Алтайский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3223, 3159, N'Амурская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3251, 3159, N'Архангельская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3282, 3159, N'Астраханская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3296, 3159, N'Башкортостан(Башкирия)', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3352, 3159, N'Белгородская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3371, 3159, N'Брянская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3407, 3159, N'Бурятия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3437, 3159, N'Владимирская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3468, 3159, N'Волгоградская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3503, 3159, N'Вологодская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3529, 3159, N'Воронежская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3563, 3159, N'Нижегородская (Горьковская)', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3630, 3159, N'Дагестан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3673, 3159, N'Еврейская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3675, 3159, N'Ивановская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3703, 3159, N'Иркутская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3751, 3159, N'Кабардино-Балкария', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3761, 3159, N'Калининградская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3784, 3159, N'Тверская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3827, 3159, N'Калмыкия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3841, 3159, N'Калужская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3872, 3159, N'Камчатская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3892, 3159, N'Карелия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3921, 3159, N'Кемеровская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3952, 3159, N'Кировская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3994, 3159, N'Коми', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4026, 3159, N'Костромская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4052, 3159, N'Краснодарский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4105, 3159, N'Красноярский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4176, 3159, N'Курганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4198, 3159, N'Курская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4227, 3159, N'Липецкая обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4243, 3159, N'Магаданская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4270, 3159, N'Марий Эл', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4287, 3159, N'Мордовия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4312, 3159, N'Москва и Московская обл.', 3)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4481, 3159, N'Мурманская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4503, 3159, N'Новгородская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4528, 3159, N'Новосибирская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4561, 3159, N'Омская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4593, 3159, N'Оренбургская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4633, 3159, N'Орловская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4657, 3159, N'Пензенская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4689, 3159, N'Пермская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4734, 3159, N'Приморский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4773, 3159, N'Псковская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4800, 3159, N'Ростовская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4861, 3159, N'Рязанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4891, 3159, N'Самарская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4925, 3159, N'Санкт-Петербург и область', 2)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4969, 3159, N'Саратовская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5011, 3159, N'Саха (Якутия)', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5052, 3159, N'Сахалин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5080, 3159, N'Свердловская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5151, 3159, N'Северная Осетия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5161, 3159, N'Смоленская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5191, 3159, N'Ставропольский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5225, 3159, N'Тамбовская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5246, 3159, N'Татарстан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5291, 3159, N'Томская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5312, 3159, N'Тува (Тувинская Респ.)', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5326, 3159, N'Тульская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5356, 3159, N'Тюменская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5404, 3159, N'Удмуртия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5432, 3159, N'Ульяновская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5458, 3159, N'Уральская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5473, 3159, N'Хабаровский край', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5507, 3159, N'Челябинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5543, 3159, N'Чечено-Ингушетия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5555, 3159, N'Читинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5600, 3159, N'Чувашия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5625, 3159, N'Ярославская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5648, 5647, N'Ahuachapan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5650, 5647, N'Cuscatlan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5652, 5647, N'La Libertad', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5654, 5647, N'La Paz', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5656, 5647, N'La Union', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5658, 5647, N'San Miguel', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5660, 5647, N'San Salvador', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5662, 5647, N'Santa Ana', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5664, 5647, N'Sonsonate', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5667, 5666, N'Trnavsky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5669, 5666, N'Братислава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5671, 5666, N'Жилина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5674, 5673, N'Osrednjeslovenska', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5676, 5673, N'Podravska', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5679, 5678, N'Paramaribo', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5682, 5681, N'Айдахо', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5694, 5681, N'Айова', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5752, 5681, N'Алабама', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5924, 5681, N'Аляска', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5927, 5681, N'Аризона', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5983, 5681, N'Арканзас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6098, 5681, N'Вайоминг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6103, 5681, N'Вашингтон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6167, 5681, N'Вермонт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6176, 5681, N'Виргиния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6242, 5681, N'Висконсин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6266, 5681, N'Гаваи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6280, 5681, N'Делавар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6291, 5681, N'Джорджия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6352, 5681, N'Западная Виргиния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6367, 5681, N'Иллинойс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6520, 5681, N'Индиана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6591, 5681, N'Калифорния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6864, 5681, N'Канзас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6917, 5681, N'Кентукки', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6973, 5681, N'Колорадо', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7015, 5681, N'Коннектикут', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7055, 5681, N'Луизиана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7120, 5681, N'Массачусетс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7228, 5681, N'Миннесота', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7288, 5681, N'Миссисипи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7411, 5681, N'Миссури', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7493, 5681, N'Мичиган', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7598, 5681, N'Монтана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7613, 5681, N'Мэн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7641, 5681, N'Мэриленд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7691, 5681, N'Небраска', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7714, 5681, N'Невада', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7733, 5681, N'Нью-Гэмпшир', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7744, 5681, N'Нью-Джерси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7859, 5681, N'Нью-Йорк', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8089, 5681, N'Нью-Мексико', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8145, 5681, N'Огайо', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8439, 5681, N'Оклахома', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8479, 5681, N'окр.Колумбия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8483, 5681, N'Орегон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8516, 5681, N'Пенсильвания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8751, 5681, N'Род-Айленд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8760, 5681, N'Северная Дакота', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8768, 5681, N'Северная Каролина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (8856, 5681, N'Теннесси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9047, 5681, N'Техас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9185, 5681, N'Флорида', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9477, 5681, N'Южная Дакота', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9489, 5681, N'Южная Каролина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9515, 5681, N'Юта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9576, 9575, N'Горно-Бадахшанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9589, 9575, N'Кулябская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9596, 9575, N'Курган-Тюбинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9605, 9575, N'Согдийская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9627, 9575, N'Таджикистан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9639, 9638, N'Ашхабадская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9653, 9638, N'Красноводская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9670, 9638, N'Марыйская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9682, 9638, N'Ташаузская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9685, 9638, N'Чарджоуская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9702, 9701, N'Grand Turk', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9706, 9705, N'Bartin', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9708, 9705, N'Bayburt', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9710, 9705, N'Karabuk', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9712, 9705, N'Адана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9714, 9705, N'Айдын', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9716, 9705, N'Амасья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9718, 9705, N'Анкара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9720, 9705, N'Анталья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9722, 9705, N'Артвин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9724, 9705, N'Афьон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9726, 9705, N'Балыкесир', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9728, 9705, N'Биледжик', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9730, 9705, N'Бурса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9732, 9705, N'Газиантеп', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9734, 9705, N'Денизли', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9736, 9705, N'Измир', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9738, 9705, N'Испарта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9740, 9705, N'Ичель', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9742, 9705, N'Кайсери', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9744, 9705, N'Карс', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9746, 9705, N'Коджаэли', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9749, 9705, N'Конья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9751, 9705, N'Кыркларели', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9753, 9705, N'Кютахья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9755, 9705, N'Малатья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9757, 9705, N'Маниса', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9759, 9705, N'Сакарья', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9761, 9705, N'Самсун', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9763, 9705, N'Сивас', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9765, 9705, N'Стамбул', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9767, 9705, N'Трабзон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9770, 9705, N'Чорум', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9772, 9705, N'Эдирне', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9774, 9705, N'Элязыг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9776, 9705, N'Эрзинджан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9778, 9705, N'Эрзурум', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9780, 9705, N'Эскишехир', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9783, 9782, N'Jinja', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9785, 9782, N'Kampala', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9788, 9787, N'Андижанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9796, 9787, N'Бухарская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9806, 9787, N'Джизакская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9813, 9787, N'Каракалпакия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9825, 9787, N'Кашкадарьинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9832, 9787, N'Навоийская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9836, 9787, N'Наманганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9844, 9787, N'Самаркандская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9851, 9787, N'Сурхандарьинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9859, 9787, N'Сырдарьинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9869, 9787, N'Ташкентская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9892, 9787, N'Ферганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9905, 9787, N'Хорезмская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9909, 9908, N'Винницкая обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9943, 9908, N'Волынская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (9964, 9908, N'Днепропетровская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10002, 9908, N'Донецкая обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10061, 9908, N'Житомирская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10094, 9908, N'Закарпатская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10111, 9908, N'Запорожская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10133, 9908, N'Ивано-Франковская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10165, 9908, N'Киевская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10201, 9908, N'Кировоградская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10227, 9908, N'Крымская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10259, 9908, N'Луганская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10318, 9908, N'Львовская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10354, 9908, N'Николаевская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10373, 9908, N'Одесская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10407, 9908, N'Полтавская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10437, 9908, N'Ровенская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10455, 9908, N'Сумская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10480, 9908, N'Тернопольская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10504, 9908, N'Харьковская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10535, 9908, N'Херсонская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10559, 9908, N'Хмельницкая обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10583, 9908, N'Черкасская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10607, 9908, N'Черниговская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10633, 9908, N'Черновицкая обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10649, 10648, N'Etela-Karjala', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10651, 10648, N'Paijat-Hame', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10653, 10648, N'Pohjanmaa', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10655, 10648, N'Pohjois-Pohjanmaa', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10657, 10648, N'Pohjois-Savo', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10659, 10648, N'Satakunta', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10661, 10648, N'Varsinais-Suomi', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10663, 10648, N'Кески-Суоми', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10665, 10648, N'Усима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10669, 10668, N'Cotes-dArmor', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10671, 10668, N'Алье', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10673, 10668, N'Альпы Верхние', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10675, 10668, N'Альпы Приморские', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10679, 10668, N'Арденны', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10681, 10668, N'Бельфор', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10683, 10668, N'Буш-дю-Рон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10686, 10668, N'Валь-д Уаз', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10688, 10668, N'Валь-де-Марн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10699, 10668, N'Вар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10702, 10668, N'Вогезы', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10704, 10668, N'Воклюз', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10706, 10668, N'Вьенна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10708, 10668, N'Вьенна Верхняя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10710, 10668, N'Гар', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10712, 10668, N'Гаронна Верхняя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10714, 10668, N'Дё-Севр', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10716, 10668, N'Дром', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10719, 10668, N'Ду', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10721, 10668, N'Жиронда', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10723, 10668, N'Ивелин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10725, 10668, N'Иль и Виден', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10728, 10668, N'Коррез', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10730, 10668, N'Корсика Верхняя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10732, 10668, N'Корсика Южная', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10734, 10668, N'Кот-дОр', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10736, 10668, N'Ланды', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10738, 10668, N'Ло и Гаронна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10740, 10668, N'Лозер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10742, 10668, N'Луар и Шер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10744, 10668, N'Луара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10747, 10668, N'Луара Атлантическая', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10750, 10668, N'Луара Верхняя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10752, 10668, N'Луаре', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10754, 10668, N'Майенн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10756, 10668, N'Марна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10759, 10668, N'Мен и Луара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10762, 10668, N'Мёрт и Мозель', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10764, 10668, N'Мозель', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10766, 10668, N'Морбиан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10768, 10668, N'Нор', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10774, 10668, N'Ньевр', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10776, 10668, N'О-де-Сен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10794, 10668, N'Об', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10796, 10668, N'Од', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10798, 10668, N'Орн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10800, 10668, N'Па-де-Кале', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10804, 10668, N'Париж', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10806, 10668, N'Пиренеи Атлантические', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10809, 10668, N'Пиренеи Верхние', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10811, 10668, N'Пиренеи Восточные', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10813, 10668, N'Рейн Верхний', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10817, 10668, N'Рейн Нижний', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10819, 10668, N'Рона', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10823, 10668, N'Савойя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10825, 10668, N'Савойя Верхняя', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10827, 10668, N'Сарта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10829, 10668, N'Сен-Сен-Дени', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10841, 10668, N'Сена Приморская', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10844, 10668, N'Сомма', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10846, 10668, N'Сона и Луара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10849, 10668, N'Тарн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10851, 10668, N'Уаза', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10853, 10668, N'Финистер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10856, 10668, N'Шаранта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10858, 10668, N'Шаранта Приморская', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10860, 10668, N'Шер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10862, 10668, N'Эна', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10864, 10668, N'Эндр', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10866, 10668, N'Эндр и Луара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10868, 10668, N'Эр', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10870, 10668, N'Эро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10872, 10668, N'Эссонн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10875, 10874, N'Jihochesky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10877, 10874, N'Jihomoravsky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10879, 10874, N'Karlovarsky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10881, 10874, N'Kralovehradecky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10883, 10874, N'Liberecky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10886, 10874, N'Moravskoslezsky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10892, 10874, N'Olomoucky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10896, 10874, N'Stredochesky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10898, 10874, N'Ustecky', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10905, 10904, N'Аргау', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10908, 10904, N'Базель-Штадт', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10910, 10904, N'Берн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10914, 10904, N'Во', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10916, 10904, N'Женева', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10918, 10904, N'Золотурн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10920, 10904, N'Люцерн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10922, 10904, N'Невшатель', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10925, 10904, N'Тичино', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10927, 10904, N'Фрибур', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10930, 10904, N'Цюрих', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10934, 10933, N'Skine', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10938, 10933, N'Vastra Gotaland', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10942, 10933, N'Вермланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10944, 10933, N'Вестерботтен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10946, 10933, N'Вестернорланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10948, 10933, N'Вестманланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10950, 10933, N'Евлеборг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10952, 10933, N'Емтланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10954, 10933, N'Йёнчёпинг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10956, 10933, N'Сёдерманланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10958, 10933, N'Стокгольм', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10962, 10933, N'Упсала', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10964, 10933, N'Халланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10966, 10933, N'Эстерйетланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (10969, 10968, N'Эстония', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11003, 11002, N'Воеводина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11008, 11002, N'Косово', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11010, 11002, N'Сербия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11015, 11014, N'Cheju', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11017, 11014, N'Chollabuk', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11020, 11014, N'Chollanam', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11024, 11014, N'Chungcheongbuk', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11027, 11014, N'Chungcheongnam', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11029, 11014, N'Incheon', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11031, 11014, N'Kangweon', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11035, 11014, N'Kwangju', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11037, 11014, N'Kyeonggi', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11040, 11014, N'Kyeongsangbuk', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11045, 11014, N'Kyeongsangnam', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11050, 11014, N'Pusan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11052, 11014, N'Seoul', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11054, 11014, N'Taegu', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11056, 11014, N'Taejeon', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11058, 11014, N'Ulsan', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11061, 11060, N'Айти', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11068, 11060, N'Акита', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11074, 11060, N'Аомори', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11080, 11060, N'Вакаяма', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11083, 11060, N'Гифу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11088, 11060, N'Гумма', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11094, 11060, N'Ибараки', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11102, 11060, N'Ивате', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11108, 11060, N'Исикава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11113, 11060, N'Кагава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11116, 11060, N'Кагосима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11121, 11060, N'Канагава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11133, 11060, N'Киото', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11139, 11060, N'Коти', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11142, 11060, N'Кумамото', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11146, 11060, N'Миэ', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11151, 11060, N'Мияги', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11155, 11060, N'Миядзаки', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11162, 11060, N'Нагано', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11168, 11060, N'Нагасаки', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11173, 11060, N'Нара', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11178, 11060, N'Ниигата', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11185, 11060, N'Окаяма', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11189, 11060, N'Окинава', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11192, 11060, N'Осака', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11209, 11060, N'Сага', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11215, 11060, N'Сайтама', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11227, 11060, N'Сига', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11230, 11060, N'Сидзуока', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11233, 11060, N'Симане', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11248, 11060, N'Тиба', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11261, 11060, N'Токио', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11270, 11060, N'Токусима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11273, 11060, N'Тотиги', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11279, 11060, N'Тоттори', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11283, 11060, N'Тояма', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11289, 11060, N'Фукуи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11295, 11060, N'Фукуока', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11304, 11060, N'Фукусима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11307, 11060, N'Хиросима', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11312, 11060, N'Хоккайдо', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11330, 11060, N'Хпого', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11340, 11060, N'Эхиме', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11346, 11060, N'Ямагата', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11354, 11060, N'Ямагути', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11363, 11060, N'Яманаси', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277552, 277551, N'Нидерланды', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277554, 277553, N'Хорватия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277556, 277555, N'Румыния', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277558, 277557, N'Гонконг', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277560, 277559, N'Индонезия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277562, 277561, N'Иордания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277564, 277563, N'Малайзия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277566, 277565, N'Сингапур', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277568, 277567, N'Тайвань', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277570, 277569, N'Туркмения', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277654, 245, N'Армения', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277655, 1894, N'Казахстан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277656, 9908, N'Украина', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277657, 616, N'Великобритания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277658, 11002, N'Югославия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277659, 63, N'Австрия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277660, 428, N'Болгария', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277661, 1707, N'Испания', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277662, 404, N'Бельгия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277663, 1012, N'Германия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277664, 2897, N'Польша', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277665, 10933, N'Швеция', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277666, 10904, N'Швейцария', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277667, 10648, N'Финляндия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277668, 1786, N'Италия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277669, 10668, N'Франция', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277670, 10874, N'Чехия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277671, 5673, N'Словения', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277672, 5681, N'США', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277673, 1451, N'Индия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (277674, 1380, N'Египет', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1923301, 582067, N'Дамаск', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1924623, 2880, N'Нордланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1930798, 582105, N'Остров Мэн', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1934356, 1894, N'Западно-Казахстанская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (1998532, 3159, N'Адыгея', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2077237, 1366, N'Хельсингор', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2284951, 3141, N'Фаро', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2316497, 3159, N'Хакасия', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2316780, 582051, N'Дубаи', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2331485, 1366, N'Копенгаген', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2412885, 582031, N'Сантьяго', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2415585, 3159, N'Чукотский АО', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2416357, 1786, N'о. Сан-Джорджо Маджоре', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2483267, 582077, N'Гавана', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2494137, 582060, N'Бейрут', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2499002, 3159, N'Ханты-Мансийский АО', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2505921, 2505884, N'Бейрут', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2564700, 1894, N'Акмолинская обл.', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2567441, 2567393, N'Тегусигальпа', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2577870, 2880, N'Ромсдал', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2578001, 2577958, N'Санто-доминго', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2687732, 2687701, N'Улан-батор', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (2713529, 10648, N'Kouvola', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3024114, 1012, N'Саарлэнд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3331120, 2374, N'Пекин', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3409961, 1380, N'Синай', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3410574, 3410238, N'Багдад', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3410602, 3410238, N'Басра', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3410645, 3410238, N'Мосул', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3661590, 3661568, N'Йоханесбург', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (3663676, 582041, N'Скопье', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4042477, 582065, N'Морокко', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4093580, 1707, N'Gerona', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4119771, 582065, N'Танжер', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4691804, 2374, N'Гуандон', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (4778004, 10933, N'Норрботтен', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5019394, 3159, N'Ямало-Ненецкий АО', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5556213, 582046, N'Перу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5640357, 10648, N'Pohjois-Karjala', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (5640862, 582090, N'Tunisia', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6128546, 582050, N'Тайланд', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6128641, 1258, N'Корфу', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6128697, 582082, N'Мозамбик', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6453632, 582040, N'Korea', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (6460443, 582043, N'Мальта', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7593366, 582044, N'Пакистан', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7716133, 7716093, N'Арулько', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (7719907, 582064, N'Пичинча', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11564803, 582029, N'Багамы', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (11566007, 582040, N'Южная Корея', 0)
INSERT INTO [dbo].[Regions] ([Id], [CountryId], [Name], [Priority]) VALUES (15789405, 582106, N'Ямайка', 0)